# configs/docker.yaml
env: "docker"

http_server:
  address: ":8080"
  timeout: 10s
  idle_timeout: 90s

telegram:
  # Используем пустые строки вместо подстановок переменных ${...}
  token: ""  # Будет заменено переменной окружения TELEGRAM_TOKEN
  admin_id: 0  # Будет заменено переменной окружения TELEGRAM_ADMIN_ID
  provider_token: ""  # Будет заменено переменной окружения TELEGRAM_PROVIDER_TOKEN

mongodb:
  uri: ""  # Будет заменено переменной окружения MONGO_URI
  db_name: ""  # Будет заменено переменной окружения MONGO_DB_NAME
  user_collection: "users"
  server_collection: "servers"
  plan_collection: "plans"
  subscription_collection: "subscriptions"
  payment_collection: "payments"
  referral_collection: "referrals"
  faq_collection: "faqs"
  instruction_collection: "instructions"

xui:
  api_timeout: 15s

yookassa:
  shop_id: ""  # Будет заменено переменной окружения YOOKASSA_SHOP_ID
  secret_key: ""  # Будет заменено переменной окружения YOOKASSA_SECRET_KEY
  return_url: ""  # Будет заменено переменной окружения YOOKASSA_RETURN_URL
  webhook_secret: ""  # Может быть заменено переменной окружения YOOKASSA_WEBHOOK_SECRET