# configs/docker.yaml
env: "docker"

http_server:
  # address: "${HTTP_ADDRESS}"
  noop: null

telegram:
  token: "${TELEGRAM_API_TOKEN}"
  provider_token: "${TELEGRAM_PROVIDER_TOKEN}"

mongodb:
  uri: "mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}"
  db_name: "${MONGO_DB}"
  user_collection: "users"
  server_collection: "servers"
  plan_collection: "plans"
  subscription_collection: "subscriptions"
  payment_collection: "payments"
  faq_collection: "faqs"
  instruction_collection: "instructions"
  referral_collection: "referrals"

xui:
  noop: null

yookassa:
  shop_id: "${YOOKASSA_SHOP_ID}"
  secret_key: "${YOOKASSA_SECRET_KEY}"
  return_url: "${YOOKASSA_RETURN_URL}"
  webhook_key: "${YOOKASSA_WEBHOOK_KEY}"

workers:
  noop: null